# Build
FROM node:22 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Servir build
FROM node:22-slim

WORKDIR /app
RUN npm install -g http-server

COPY --from=builder /app/dist /app/dist

EXPOSE 5180

CMD ["http-server", "dist", "-p", "5180"]
